# Generated by Django 4.2.5 on 2023-11-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name="Patient's First Name"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Patient's Last Name"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(max_length=10, verbose_name="Patient's Mobile Number"),
        ),
    ]
