# Generated by Django 4.2.5 on 2023-11-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='htype',
            new_name='category',
        ),
    ]
