# Generated by Django 4.2.5 on 2023-11-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_htype_hospital_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Hospital_Type',
        ),
    ]
