# Generated by Django 4.2.5 on 2023-11-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_employeeregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeRegistration',
        ),
    ]
