# Generated by Django 4.2.5 on 2023-11-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_employeeregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeRegistration',
        ),
    ]
