# Generated by Django 4.2.5 on 2023-11-22 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import policy_premium.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberToInsure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible_members', models.CharField(choices=[('Self', 'Self'), ('Spouse', 'Spouse'), ('Son/Daughter', 'Son/Daughter'), ('Parents/In-laws', 'Parents/In-laws')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('coverage_details', models.CharField(max_length=255)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eligible_members', models.ManyToManyField(blank=True, to='policy_premium.membertoinsure')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_premium.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('current_address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('nominee_name', models.CharField(max_length=255)),
                ('nominee_relation', models.CharField(max_length=50)),
                ('nominee_date_of_birth', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(default=policy_premium.models.generate_transaction_id, max_length=255)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_premium.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('policy_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_premium.policyholder')),
            ],
        ),
        migrations.CreateModel(
            name='HealthDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_existing_disease', models.BooleanField()),
                ('policy_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_premium.policyholder')),
                ('selected_diseases', models.ManyToManyField(blank=True, to='policy_premium.selecteddisease')),
            ],
        ),
    ]
